CREATE TABLE `regeneration_requests` (
	`id` text PRIMARY KEY NOT NULL,
	`session_id` text NOT NULL,
	`plan_id` text NOT NULL,
	`revision_id` text NOT NULL,
	`context_event_id` text,
	`transcript_chunk_id` text,
	`target_section` text,
	`target_start_line` integer,
	`target_end_line` integer,
	`highlighted_text` text,
	`user_instruction` text NOT NULL,
	`transcript_window_start` integer,
	`transcript_window_end` integer,
	`status` text DEFAULT 'detected' NOT NULL,
	`generated_content` text,
	`original_content` text,
	`applied` integer DEFAULT 0 NOT NULL,
	`created_at` integer DEFAULT (unixepoch() * 1000) NOT NULL,
	`completed_at` integer,
	`created_by` text NOT NULL,
	FOREIGN KEY (`session_id`) REFERENCES `plan_sessions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`plan_id`) REFERENCES `plans`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`revision_id`) REFERENCES `revisions`(`id`) ON UPDATE no action ON DELETE cascade,
	FOREIGN KEY (`context_event_id`) REFERENCES `context_events`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`transcript_chunk_id`) REFERENCES `transcript_chunks`(`id`) ON UPDATE no action ON DELETE no action,
	FOREIGN KEY (`created_by`) REFERENCES `user`(`id`) ON UPDATE no action ON DELETE no action
);
