/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as PlanNewRouteRouteImport } from './routes/plan/new/route'
import { Route as PlanPlanIdIndexRouteImport } from './routes/plan/$planId/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as PlanPlanIdHistoryRouteRouteImport } from './routes/plan/$planId/history/route'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanNewRouteRoute = PlanNewRouteRouteImport.update({
  id: '/plan/new',
  path: '/plan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPlanIdIndexRoute = PlanPlanIdIndexRouteImport.update({
  id: '/plan/$planId/',
  path: '/plan/$planId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPlanIdHistoryRouteRoute = PlanPlanIdHistoryRouteRouteImport.update({
  id: '/plan/$planId/history',
  path: '/plan/$planId/history',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/plan/new': typeof PlanNewRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/plan/$planId/history': typeof PlanPlanIdHistoryRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/plan/$planId/': typeof PlanPlanIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/plan/new': typeof PlanNewRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/plan/$planId/history': typeof PlanPlanIdHistoryRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/plan/$planId': typeof PlanPlanIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/plan/new': typeof PlanNewRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/plan/$planId/history': typeof PlanPlanIdHistoryRouteRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/plan/$planId/': typeof PlanPlanIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/plan/new'
    | '/sign-in/$'
    | '/plan/$planId/history'
    | '/api/auth/$'
    | '/plan/$planId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/plan/new'
    | '/sign-in/$'
    | '/plan/$planId/history'
    | '/api/auth/$'
    | '/plan/$planId'
  id:
    | '__root__'
    | '/'
    | '/plan/new'
    | '/sign-in/$'
    | '/plan/$planId/history'
    | '/api/auth/$'
    | '/plan/$planId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PlanNewRouteRoute: typeof PlanNewRouteRoute
  SignInSplatRoute: typeof SignInSplatRoute
  PlanPlanIdHistoryRouteRoute: typeof PlanPlanIdHistoryRouteRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  PlanPlanIdIndexRoute: typeof PlanPlanIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/new': {
      id: '/plan/new'
      path: '/plan/new'
      fullPath: '/plan/new'
      preLoaderRoute: typeof PlanNewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$planId/': {
      id: '/plan/$planId/'
      path: '/plan/$planId'
      fullPath: '/plan/$planId/'
      preLoaderRoute: typeof PlanPlanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$planId/history': {
      id: '/plan/$planId/history'
      path: '/plan/$planId/history'
      fullPath: '/plan/$planId/history'
      preLoaderRoute: typeof PlanPlanIdHistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PlanNewRouteRoute: PlanNewRouteRoute,
  SignInSplatRoute: SignInSplatRoute,
  PlanPlanIdHistoryRouteRoute: PlanPlanIdHistoryRouteRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  PlanPlanIdIndexRoute: PlanPlanIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
