/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in/$'
import { Route as PlanNewRouteRouteImport } from './routes/plan/new/route'
import { Route as HandoffPublicSlugRouteRouteImport } from './routes/handoff/$publicSlug/route'
import { Route as PlanPlanIdIndexRouteImport } from './routes/plan/$planId/index'
import { Route as ApiHandoffsSnapshotIdRouteImport } from './routes/api/handoffs/$snapshotId'
import { Route as PlanPlanIdSessionsRouteRouteImport } from './routes/plan/$planId/sessions/route'
import { Route as PlanPlanIdHistoryRouteRouteImport } from './routes/plan/$planId/history/route'
import { Route as ApiSessionsSessionIdTranscriptRouteImport } from './routes/api/sessions/$sessionId/transcript'
import { Route as ApiSessionsSessionIdTranscribeRouteImport } from './routes/api/sessions/$sessionId/transcribe'
import { Route as ApiSessionsSessionIdContextRouteImport } from './routes/api/sessions/$sessionId/context'
import { Route as ApiHandoffsSnapshotIdAgentRunsRouteImport } from './routes/api/handoffs/$snapshotId/agent-runs'
import { Route as ApiSessionsSessionIdRegenerationIndexRouteImport } from './routes/api/sessions/$sessionId/regeneration/index'
import { Route as ApiSessionsSessionIdRegenerationRequestIdRouteImport } from './routes/api/sessions/$sessionId/regeneration/$requestId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanNewRouteRoute = PlanNewRouteRouteImport.update({
  id: '/plan/new',
  path: '/plan/new',
  getParentRoute: () => rootRouteImport,
} as any)
const HandoffPublicSlugRouteRoute = HandoffPublicSlugRouteRouteImport.update({
  id: '/handoff/$publicSlug',
  path: '/handoff/$publicSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPlanIdIndexRoute = PlanPlanIdIndexRouteImport.update({
  id: '/plan/$planId/',
  path: '/plan/$planId/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHandoffsSnapshotIdRoute = ApiHandoffsSnapshotIdRouteImport.update({
  id: '/api/handoffs/$snapshotId',
  path: '/api/handoffs/$snapshotId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPlanIdSessionsRouteRoute = PlanPlanIdSessionsRouteRouteImport.update({
  id: '/plan/$planId/sessions',
  path: '/plan/$planId/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanPlanIdHistoryRouteRoute = PlanPlanIdHistoryRouteRouteImport.update({
  id: '/plan/$planId/history',
  path: '/plan/$planId/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSessionsSessionIdTranscriptRoute =
  ApiSessionsSessionIdTranscriptRouteImport.update({
    id: '/api/sessions/$sessionId/transcript',
    path: '/api/sessions/$sessionId/transcript',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsSessionIdTranscribeRoute =
  ApiSessionsSessionIdTranscribeRouteImport.update({
    id: '/api/sessions/$sessionId/transcribe',
    path: '/api/sessions/$sessionId/transcribe',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsSessionIdContextRoute =
  ApiSessionsSessionIdContextRouteImport.update({
    id: '/api/sessions/$sessionId/context',
    path: '/api/sessions/$sessionId/context',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHandoffsSnapshotIdAgentRunsRoute =
  ApiHandoffsSnapshotIdAgentRunsRouteImport.update({
    id: '/agent-runs',
    path: '/agent-runs',
    getParentRoute: () => ApiHandoffsSnapshotIdRoute,
  } as any)
const ApiSessionsSessionIdRegenerationIndexRoute =
  ApiSessionsSessionIdRegenerationIndexRouteImport.update({
    id: '/api/sessions/$sessionId/regeneration/',
    path: '/api/sessions/$sessionId/regeneration/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiSessionsSessionIdRegenerationRequestIdRoute =
  ApiSessionsSessionIdRegenerationRequestIdRouteImport.update({
    id: '/api/sessions/$sessionId/regeneration/$requestId',
    path: '/api/sessions/$sessionId/regeneration/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/handoff/$publicSlug': typeof HandoffPublicSlugRouteRoute
  '/plan/new': typeof PlanNewRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/plan/$planId/history': typeof PlanPlanIdHistoryRouteRoute
  '/plan/$planId/sessions': typeof PlanPlanIdSessionsRouteRoute
  '/api/handoffs/$snapshotId': typeof ApiHandoffsSnapshotIdRouteWithChildren
  '/plan/$planId/': typeof PlanPlanIdIndexRoute
  '/api/handoffs/$snapshotId/agent-runs': typeof ApiHandoffsSnapshotIdAgentRunsRoute
  '/api/sessions/$sessionId/context': typeof ApiSessionsSessionIdContextRoute
  '/api/sessions/$sessionId/transcribe': typeof ApiSessionsSessionIdTranscribeRoute
  '/api/sessions/$sessionId/transcript': typeof ApiSessionsSessionIdTranscriptRoute
  '/api/sessions/$sessionId/regeneration/$requestId': typeof ApiSessionsSessionIdRegenerationRequestIdRoute
  '/api/sessions/$sessionId/regeneration/': typeof ApiSessionsSessionIdRegenerationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/handoff/$publicSlug': typeof HandoffPublicSlugRouteRoute
  '/plan/new': typeof PlanNewRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/plan/$planId/history': typeof PlanPlanIdHistoryRouteRoute
  '/plan/$planId/sessions': typeof PlanPlanIdSessionsRouteRoute
  '/api/handoffs/$snapshotId': typeof ApiHandoffsSnapshotIdRouteWithChildren
  '/plan/$planId': typeof PlanPlanIdIndexRoute
  '/api/handoffs/$snapshotId/agent-runs': typeof ApiHandoffsSnapshotIdAgentRunsRoute
  '/api/sessions/$sessionId/context': typeof ApiSessionsSessionIdContextRoute
  '/api/sessions/$sessionId/transcribe': typeof ApiSessionsSessionIdTranscribeRoute
  '/api/sessions/$sessionId/transcript': typeof ApiSessionsSessionIdTranscriptRoute
  '/api/sessions/$sessionId/regeneration/$requestId': typeof ApiSessionsSessionIdRegenerationRequestIdRoute
  '/api/sessions/$sessionId/regeneration': typeof ApiSessionsSessionIdRegenerationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/handoff/$publicSlug': typeof HandoffPublicSlugRouteRoute
  '/plan/new': typeof PlanNewRouteRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/plan/$planId/history': typeof PlanPlanIdHistoryRouteRoute
  '/plan/$planId/sessions': typeof PlanPlanIdSessionsRouteRoute
  '/api/handoffs/$snapshotId': typeof ApiHandoffsSnapshotIdRouteWithChildren
  '/plan/$planId/': typeof PlanPlanIdIndexRoute
  '/api/handoffs/$snapshotId/agent-runs': typeof ApiHandoffsSnapshotIdAgentRunsRoute
  '/api/sessions/$sessionId/context': typeof ApiSessionsSessionIdContextRoute
  '/api/sessions/$sessionId/transcribe': typeof ApiSessionsSessionIdTranscribeRoute
  '/api/sessions/$sessionId/transcript': typeof ApiSessionsSessionIdTranscriptRoute
  '/api/sessions/$sessionId/regeneration/$requestId': typeof ApiSessionsSessionIdRegenerationRequestIdRoute
  '/api/sessions/$sessionId/regeneration/': typeof ApiSessionsSessionIdRegenerationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/handoff/$publicSlug'
    | '/plan/new'
    | '/sign-in/$'
    | '/plan/$planId/history'
    | '/plan/$planId/sessions'
    | '/api/handoffs/$snapshotId'
    | '/plan/$planId/'
    | '/api/handoffs/$snapshotId/agent-runs'
    | '/api/sessions/$sessionId/context'
    | '/api/sessions/$sessionId/transcribe'
    | '/api/sessions/$sessionId/transcript'
    | '/api/sessions/$sessionId/regeneration/$requestId'
    | '/api/sessions/$sessionId/regeneration/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/handoff/$publicSlug'
    | '/plan/new'
    | '/sign-in/$'
    | '/plan/$planId/history'
    | '/plan/$planId/sessions'
    | '/api/handoffs/$snapshotId'
    | '/plan/$planId'
    | '/api/handoffs/$snapshotId/agent-runs'
    | '/api/sessions/$sessionId/context'
    | '/api/sessions/$sessionId/transcribe'
    | '/api/sessions/$sessionId/transcript'
    | '/api/sessions/$sessionId/regeneration/$requestId'
    | '/api/sessions/$sessionId/regeneration'
  id:
    | '__root__'
    | '/'
    | '/handoff/$publicSlug'
    | '/plan/new'
    | '/sign-in/$'
    | '/plan/$planId/history'
    | '/plan/$planId/sessions'
    | '/api/handoffs/$snapshotId'
    | '/plan/$planId/'
    | '/api/handoffs/$snapshotId/agent-runs'
    | '/api/sessions/$sessionId/context'
    | '/api/sessions/$sessionId/transcribe'
    | '/api/sessions/$sessionId/transcript'
    | '/api/sessions/$sessionId/regeneration/$requestId'
    | '/api/sessions/$sessionId/regeneration/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HandoffPublicSlugRouteRoute: typeof HandoffPublicSlugRouteRoute
  PlanNewRouteRoute: typeof PlanNewRouteRoute
  SignInSplatRoute: typeof SignInSplatRoute
  PlanPlanIdHistoryRouteRoute: typeof PlanPlanIdHistoryRouteRoute
  PlanPlanIdSessionsRouteRoute: typeof PlanPlanIdSessionsRouteRoute
  ApiHandoffsSnapshotIdRoute: typeof ApiHandoffsSnapshotIdRouteWithChildren
  PlanPlanIdIndexRoute: typeof PlanPlanIdIndexRoute
  ApiSessionsSessionIdContextRoute: typeof ApiSessionsSessionIdContextRoute
  ApiSessionsSessionIdTranscribeRoute: typeof ApiSessionsSessionIdTranscribeRoute
  ApiSessionsSessionIdTranscriptRoute: typeof ApiSessionsSessionIdTranscriptRoute
  ApiSessionsSessionIdRegenerationRequestIdRoute: typeof ApiSessionsSessionIdRegenerationRequestIdRoute
  ApiSessionsSessionIdRegenerationIndexRoute: typeof ApiSessionsSessionIdRegenerationIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/new': {
      id: '/plan/new'
      path: '/plan/new'
      fullPath: '/plan/new'
      preLoaderRoute: typeof PlanNewRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/handoff/$publicSlug': {
      id: '/handoff/$publicSlug'
      path: '/handoff/$publicSlug'
      fullPath: '/handoff/$publicSlug'
      preLoaderRoute: typeof HandoffPublicSlugRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$planId/': {
      id: '/plan/$planId/'
      path: '/plan/$planId'
      fullPath: '/plan/$planId/'
      preLoaderRoute: typeof PlanPlanIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoffs/$snapshotId': {
      id: '/api/handoffs/$snapshotId'
      path: '/api/handoffs/$snapshotId'
      fullPath: '/api/handoffs/$snapshotId'
      preLoaderRoute: typeof ApiHandoffsSnapshotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$planId/sessions': {
      id: '/plan/$planId/sessions'
      path: '/plan/$planId/sessions'
      fullPath: '/plan/$planId/sessions'
      preLoaderRoute: typeof PlanPlanIdSessionsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan/$planId/history': {
      id: '/plan/$planId/history'
      path: '/plan/$planId/history'
      fullPath: '/plan/$planId/history'
      preLoaderRoute: typeof PlanPlanIdHistoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/transcript': {
      id: '/api/sessions/$sessionId/transcript'
      path: '/api/sessions/$sessionId/transcript'
      fullPath: '/api/sessions/$sessionId/transcript'
      preLoaderRoute: typeof ApiSessionsSessionIdTranscriptRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/transcribe': {
      id: '/api/sessions/$sessionId/transcribe'
      path: '/api/sessions/$sessionId/transcribe'
      fullPath: '/api/sessions/$sessionId/transcribe'
      preLoaderRoute: typeof ApiSessionsSessionIdTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/context': {
      id: '/api/sessions/$sessionId/context'
      path: '/api/sessions/$sessionId/context'
      fullPath: '/api/sessions/$sessionId/context'
      preLoaderRoute: typeof ApiSessionsSessionIdContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/handoffs/$snapshotId/agent-runs': {
      id: '/api/handoffs/$snapshotId/agent-runs'
      path: '/agent-runs'
      fullPath: '/api/handoffs/$snapshotId/agent-runs'
      preLoaderRoute: typeof ApiHandoffsSnapshotIdAgentRunsRouteImport
      parentRoute: typeof ApiHandoffsSnapshotIdRoute
    }
    '/api/sessions/$sessionId/regeneration/': {
      id: '/api/sessions/$sessionId/regeneration/'
      path: '/api/sessions/$sessionId/regeneration'
      fullPath: '/api/sessions/$sessionId/regeneration/'
      preLoaderRoute: typeof ApiSessionsSessionIdRegenerationIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sessions/$sessionId/regeneration/$requestId': {
      id: '/api/sessions/$sessionId/regeneration/$requestId'
      path: '/api/sessions/$sessionId/regeneration/$requestId'
      fullPath: '/api/sessions/$sessionId/regeneration/$requestId'
      preLoaderRoute: typeof ApiSessionsSessionIdRegenerationRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ApiHandoffsSnapshotIdRouteChildren {
  ApiHandoffsSnapshotIdAgentRunsRoute: typeof ApiHandoffsSnapshotIdAgentRunsRoute
}

const ApiHandoffsSnapshotIdRouteChildren: ApiHandoffsSnapshotIdRouteChildren = {
  ApiHandoffsSnapshotIdAgentRunsRoute: ApiHandoffsSnapshotIdAgentRunsRoute,
}

const ApiHandoffsSnapshotIdRouteWithChildren =
  ApiHandoffsSnapshotIdRoute._addFileChildren(
    ApiHandoffsSnapshotIdRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HandoffPublicSlugRouteRoute: HandoffPublicSlugRouteRoute,
  PlanNewRouteRoute: PlanNewRouteRoute,
  SignInSplatRoute: SignInSplatRoute,
  PlanPlanIdHistoryRouteRoute: PlanPlanIdHistoryRouteRoute,
  PlanPlanIdSessionsRouteRoute: PlanPlanIdSessionsRouteRoute,
  ApiHandoffsSnapshotIdRoute: ApiHandoffsSnapshotIdRouteWithChildren,
  PlanPlanIdIndexRoute: PlanPlanIdIndexRoute,
  ApiSessionsSessionIdContextRoute: ApiSessionsSessionIdContextRoute,
  ApiSessionsSessionIdTranscribeRoute: ApiSessionsSessionIdTranscribeRoute,
  ApiSessionsSessionIdTranscriptRoute: ApiSessionsSessionIdTranscriptRoute,
  ApiSessionsSessionIdRegenerationRequestIdRoute:
    ApiSessionsSessionIdRegenerationRequestIdRoute,
  ApiSessionsSessionIdRegenerationIndexRoute:
    ApiSessionsSessionIdRegenerationIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
